import { Vector3 } from "three";

/** Pre-built land lookup grid (generated by scripts/generate-land-grid.mjs). */
export const WORLD_LAND_GRID_URL = "/maps/world-land-grid.bin";

/** Precomputed lat/lon land lookup derived from Natural Earth GeoJSON. */
export interface LandGrid {
  latMin: number;
  latStep: number;
  latCount: number;
  lonMin: number;
  lonStep: number;
  lonCount: number;
  data: Uint8Array;
}

export type SurfaceKind = "land" | "ocean";

export interface GlobePoint {
  lat: number;
  lon: number;
  kind: SurfaceKind;
}

const MIN_COS_LAT = 0.12;
const GRID_HEADER_BYTES = 40;

/** Match Three.js equirectangular sphere convention. */
export function latLngToUnitVector(lat: number, lon: number): Vector3 {
  const phi = ((90 - lat) * Math.PI) / 180;
  const theta = ((180 + lon) * Math.PI) / 180;
  return new Vector3(
    -Math.sin(phi) * Math.cos(theta),
    Math.cos(phi),
    Math.sin(phi) * Math.sin(theta),
  );
}

export async function loadLandGrid(url: string): Promise<LandGrid> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to load land grid: ${url}`);
  }

  const buffer = await res.arrayBuffer();
  if (buffer.byteLength < GRID_HEADER_BYTES) {
    throw new Error("Land grid file is too small");
  }

  const view = new DataView(buffer);
  const latMin = view.getFloat64(0, true);
  const latStep = view.getFloat64(8, true);
  const lonMin = view.getFloat64(16, true);
  const lonStep = view.getFloat64(24, true);
  const latCount = view.getUint32(32, true);
  const lonCount = view.getUint32(36, true);
  const expectedBytes = GRID_HEADER_BYTES + latCount * lonCount;

  if (buffer.byteLength < expectedBytes) {
    throw new Error("Land grid payload size mismatch");
  }

  return {
    latMin,
    latStep,
    latCount,
    lonMin,
    lonStep,
    lonCount,
    data: new Uint8Array(buffer, GRID_HEADER_BYTES, latCount * lonCount),
  };
}

export function sampleSurfaceKind(grid: LandGrid, lat: number, lon: number): SurfaceKind {
  const latIdx = Math.floor((lat - grid.latMin) / grid.latStep);
  if (latIdx < 0 || latIdx >= grid.latCount) {
    return "ocean";
  }

  let lonIdx = Math.floor((lon - grid.lonMin) / grid.lonStep);
  lonIdx = ((lonIdx % grid.lonCount) + grid.lonCount) % grid.lonCount;

  return grid.data[latIdx * grid.lonCount + lonIdx] ? "land" : "ocean";
}

export function buildGlobePoints(
  grid: LandGrid,
  latStep = 7,
  lonStep = 8,
): GlobePoint[] {
  const points: GlobePoint[] = [];

  for (let lat = -90 + latStep / 2; lat <= 90 - latStep / 2; lat += latStep) {
    const cosLat = Math.cos((lat * Math.PI) / 180);
    const lonStepAtLat = lonStep / Math.max(cosLat, MIN_COS_LAT);

    for (let lon = -180; lon < 180; lon += lonStepAtLat) {
      points.push({
        lat,
        lon,
        kind: sampleSurfaceKind(grid, lat, lon),
      });
    }
  }

  return points;
}

export function surfaceColor(
  kind: SurfaceKind,
  colors: { land: string; ocean: string },
): string {
  return kind === "land" ? colors.land : colors.ocean;
}
